# Generated by Django 5.0.3 on 2024-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_menuitems_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitems",
            name="ImageURL",
            field=models.CharField(max_length=255),
        ),
    ]
