# Generated by Django 5.0.3 on 2024-03-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_menuitems_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitems",
            name="ImageURL",
            field=models.ImageField(upload_to="MenuImages/"),
        ),
    ]
